// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth_user_begin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Apps.FileServerApp.Messages {

  /// <summary>Holder for reflection information generated from auth_user_begin.proto</summary>
  public static partial class AuthUserBeginReflection {

    #region Descriptor
    /// <summary>File descriptor for auth_user_begin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthUserBeginReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVhdXRoX3VzZXJfYmVnaW4ucHJvdG8ihwEKDUF1dGhVc2VyQmVnaW4SEQoJ",
            "cHJpbmNpcGFsGAEgASgMEj4KG2luaXRpYWxfdXNlcl9jaGFsbGVuZ2VfdHlw",
            "ZRgCIAEoDjIZLkluaXRpYWxVc2VyQ2hhbGxlbmdlVHlwZRIjChtpbml0aWFs",
            "X3VzZXJfY2hhbGxlbmdlX2RhdGEYAyABKAwqMgoYSW5pdGlhbFVzZXJDaGFs",
            "bGVuZ2VUeXBlEggKBE5PTkUQABIMCghQQVNTV09SRBABQiaqAiNMdXhlbG90",
            "LkFwcHMuRmlsZVNlcnZlckFwcC5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Apps.FileServerApp.Messages.AuthUserBegin), global::Luxelot.Apps.FileServerApp.Messages.AuthUserBegin.Parser, new[]{ "Principal", "InitialUserChallengeType", "InitialUserChallengeData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum InitialUserChallengeType {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("PASSWORD")] Password = 1,
  }

  #endregion

  #region Messages
  public sealed partial class AuthUserBegin : pb::IMessage<AuthUserBegin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthUserBegin> _parser = new pb::MessageParser<AuthUserBegin>(() => new AuthUserBegin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthUserBegin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Apps.FileServerApp.Messages.AuthUserBeginReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthUserBegin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthUserBegin(AuthUserBegin other) : this() {
      principal_ = other.principal_;
      initialUserChallengeType_ = other.initialUserChallengeType_;
      initialUserChallengeData_ = other.initialUserChallengeData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthUserBegin Clone() {
      return new AuthUserBegin(this);
    }

    /// <summary>Field number for the "principal" field.</summary>
    public const int PrincipalFieldNumber = 1;
    private pb::ByteString principal_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Principal {
      get { return principal_; }
      set {
        principal_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "initial_user_challenge_type" field.</summary>
    public const int InitialUserChallengeTypeFieldNumber = 2;
    private global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType initialUserChallengeType_ = global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType InitialUserChallengeType {
      get { return initialUserChallengeType_; }
      set {
        initialUserChallengeType_ = value;
      }
    }

    /// <summary>Field number for the "initial_user_challenge_data" field.</summary>
    public const int InitialUserChallengeDataFieldNumber = 3;
    private pb::ByteString initialUserChallengeData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString InitialUserChallengeData {
      get { return initialUserChallengeData_; }
      set {
        initialUserChallengeData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthUserBegin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthUserBegin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Principal != other.Principal) return false;
      if (InitialUserChallengeType != other.InitialUserChallengeType) return false;
      if (InitialUserChallengeData != other.InitialUserChallengeData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Principal.Length != 0) hash ^= Principal.GetHashCode();
      if (InitialUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType.None) hash ^= InitialUserChallengeType.GetHashCode();
      if (InitialUserChallengeData.Length != 0) hash ^= InitialUserChallengeData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Principal.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Principal);
      }
      if (InitialUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) InitialUserChallengeType);
      }
      if (InitialUserChallengeData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(InitialUserChallengeData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Principal.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Principal);
      }
      if (InitialUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) InitialUserChallengeType);
      }
      if (InitialUserChallengeData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(InitialUserChallengeData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Principal.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Principal);
      }
      if (InitialUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InitialUserChallengeType);
      }
      if (InitialUserChallengeData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(InitialUserChallengeData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthUserBegin other) {
      if (other == null) {
        return;
      }
      if (other.Principal.Length != 0) {
        Principal = other.Principal;
      }
      if (other.InitialUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType.None) {
        InitialUserChallengeType = other.InitialUserChallengeType;
      }
      if (other.InitialUserChallengeData.Length != 0) {
        InitialUserChallengeData = other.InitialUserChallengeData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Principal = input.ReadBytes();
            break;
          }
          case 16: {
            InitialUserChallengeType = (global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType) input.ReadEnum();
            break;
          }
          case 26: {
            InitialUserChallengeData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Principal = input.ReadBytes();
            break;
          }
          case 16: {
            InitialUserChallengeType = (global::Luxelot.Apps.FileServerApp.Messages.InitialUserChallengeType) input.ReadEnum();
            break;
          }
          case 26: {
            InitialUserChallengeData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
