// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth_user_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Apps.FileServerApp.Messages {

  /// <summary>Holder for reflection information generated from auth_user_response.proto</summary>
  public static partial class AuthUserResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for auth_user_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthUserResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhhdXRoX3VzZXJfcmVzcG9uc2UucHJvdG8iwgEKEEF1dGhVc2VyUmVzcG9u",
            "c2USHQoVdXNlcl9jaGFsbGVuZ2VfdGlja2V0GAEgASgGEg4KBnN0YXR1cxgC",
            "IAEoBRIWCg5zdGF0dXNfbWVzc2FnZRgDIAEoCRJECh5hZGRpdGlvbmFsX3Vz",
            "ZXJfY2hhbGxlbmdlX3R5cGUYBCABKA4yHC5BZGRpdGlvbmFsVXNlckNoYWxs",
            "ZW5nZVR5cGUSIQoZYWRkaXRpb25hbF91c2VyX2NoYWxsZW5nZRgFIAEoDCo0",
            "ChtBZGRpdGlvbmFsVXNlckNoYWxsZW5nZVR5cGUSDAoIUEFTU1dPUkQQABIH",
            "CgNPVFAQAUImqgIjTHV4ZWxvdC5BcHBzLkZpbGVTZXJ2ZXJBcHAuTWVzc2Fn",
            "ZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Apps.FileServerApp.Messages.AuthUserResponse), global::Luxelot.Apps.FileServerApp.Messages.AuthUserResponse.Parser, new[]{ "UserChallengeTicket", "Status", "StatusMessage", "AdditionalUserChallengeType", "AdditionalUserChallenge" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum AdditionalUserChallengeType {
    [pbr::OriginalName("PASSWORD")] Password = 0,
    [pbr::OriginalName("OTP")] Otp = 1,
  }

  #endregion

  #region Messages
  public sealed partial class AuthUserResponse : pb::IMessage<AuthUserResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthUserResponse> _parser = new pb::MessageParser<AuthUserResponse>(() => new AuthUserResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthUserResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Apps.FileServerApp.Messages.AuthUserResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthUserResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthUserResponse(AuthUserResponse other) : this() {
      userChallengeTicket_ = other.userChallengeTicket_;
      status_ = other.status_;
      statusMessage_ = other.statusMessage_;
      additionalUserChallengeType_ = other.additionalUserChallengeType_;
      additionalUserChallenge_ = other.additionalUserChallenge_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthUserResponse Clone() {
      return new AuthUserResponse(this);
    }

    /// <summary>Field number for the "user_challenge_ticket" field.</summary>
    public const int UserChallengeTicketFieldNumber = 1;
    private ulong userChallengeTicket_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UserChallengeTicket {
      get { return userChallengeTicket_; }
      set {
        userChallengeTicket_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private int status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "status_message" field.</summary>
    public const int StatusMessageFieldNumber = 3;
    private string statusMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StatusMessage {
      get { return statusMessage_; }
      set {
        statusMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "additional_user_challenge_type" field.</summary>
    public const int AdditionalUserChallengeTypeFieldNumber = 4;
    private global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType additionalUserChallengeType_ = global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType.Password;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType AdditionalUserChallengeType {
      get { return additionalUserChallengeType_; }
      set {
        additionalUserChallengeType_ = value;
      }
    }

    /// <summary>Field number for the "additional_user_challenge" field.</summary>
    public const int AdditionalUserChallengeFieldNumber = 5;
    private pb::ByteString additionalUserChallenge_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString AdditionalUserChallenge {
      get { return additionalUserChallenge_; }
      set {
        additionalUserChallenge_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthUserResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthUserResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserChallengeTicket != other.UserChallengeTicket) return false;
      if (Status != other.Status) return false;
      if (StatusMessage != other.StatusMessage) return false;
      if (AdditionalUserChallengeType != other.AdditionalUserChallengeType) return false;
      if (AdditionalUserChallenge != other.AdditionalUserChallenge) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserChallengeTicket != 0UL) hash ^= UserChallengeTicket.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (StatusMessage.Length != 0) hash ^= StatusMessage.GetHashCode();
      if (AdditionalUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType.Password) hash ^= AdditionalUserChallengeType.GetHashCode();
      if (AdditionalUserChallenge.Length != 0) hash ^= AdditionalUserChallenge.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserChallengeTicket != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(UserChallengeTicket);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Status);
      }
      if (StatusMessage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StatusMessage);
      }
      if (AdditionalUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType.Password) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AdditionalUserChallengeType);
      }
      if (AdditionalUserChallenge.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(AdditionalUserChallenge);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserChallengeTicket != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(UserChallengeTicket);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Status);
      }
      if (StatusMessage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StatusMessage);
      }
      if (AdditionalUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType.Password) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AdditionalUserChallengeType);
      }
      if (AdditionalUserChallenge.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(AdditionalUserChallenge);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserChallengeTicket != 0UL) {
        size += 1 + 8;
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (StatusMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StatusMessage);
      }
      if (AdditionalUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType.Password) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AdditionalUserChallengeType);
      }
      if (AdditionalUserChallenge.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(AdditionalUserChallenge);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthUserResponse other) {
      if (other == null) {
        return;
      }
      if (other.UserChallengeTicket != 0UL) {
        UserChallengeTicket = other.UserChallengeTicket;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.StatusMessage.Length != 0) {
        StatusMessage = other.StatusMessage;
      }
      if (other.AdditionalUserChallengeType != global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType.Password) {
        AdditionalUserChallengeType = other.AdditionalUserChallengeType;
      }
      if (other.AdditionalUserChallenge.Length != 0) {
        AdditionalUserChallenge = other.AdditionalUserChallenge;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            UserChallengeTicket = input.ReadFixed64();
            break;
          }
          case 16: {
            Status = input.ReadInt32();
            break;
          }
          case 26: {
            StatusMessage = input.ReadString();
            break;
          }
          case 32: {
            AdditionalUserChallengeType = (global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType) input.ReadEnum();
            break;
          }
          case 42: {
            AdditionalUserChallenge = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            UserChallengeTicket = input.ReadFixed64();
            break;
          }
          case 16: {
            Status = input.ReadInt32();
            break;
          }
          case 26: {
            StatusMessage = input.ReadString();
            break;
          }
          case 32: {
            AdditionalUserChallengeType = (global::Luxelot.Apps.FileServerApp.Messages.AdditionalUserChallengeType) input.ReadEnum();
            break;
          }
          case 42: {
            AdditionalUserChallenge = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
