// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: directed_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Messages {

  /// <summary>Holder for reflection information generated from directed_message.proto</summary>
  public static partial class DirectedMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for directed_message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DirectedMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZkaXJlY3RlZF9tZXNzYWdlLnByb3RvIo0BCg9EaXJlY3RlZE1lc3NhZ2US",
            "Kgoic3JjX2lkZW50aXR5X3B1YmxpY19rZXlfdGh1bWJwcmludBgBIAEoDBIq",
            "CiJkc3RfaWRlbnRpdHlfcHVibGljX2tleV90aHVtYnByaW50GAIgASgMEg8K",
            "B3BheWxvYWQYAyABKAwSEQoJc2lnbmF0dXJlGAQgASgMQhOqAhBMdXhlbG90",
            "Lk1lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Messages.DirectedMessage), global::Luxelot.Messages.DirectedMessage.Parser, new[]{ "SrcIdentityPublicKeyThumbprint", "DstIdentityPublicKeyThumbprint", "Payload", "Signature" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DirectedMessage : pb::IMessage<DirectedMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DirectedMessage> _parser = new pb::MessageParser<DirectedMessage>(() => new DirectedMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DirectedMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Messages.DirectedMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectedMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectedMessage(DirectedMessage other) : this() {
      srcIdentityPublicKeyThumbprint_ = other.srcIdentityPublicKeyThumbprint_;
      dstIdentityPublicKeyThumbprint_ = other.dstIdentityPublicKeyThumbprint_;
      payload_ = other.payload_;
      signature_ = other.signature_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectedMessage Clone() {
      return new DirectedMessage(this);
    }

    /// <summary>Field number for the "src_identity_public_key_thumbprint" field.</summary>
    public const int SrcIdentityPublicKeyThumbprintFieldNumber = 1;
    private pb::ByteString srcIdentityPublicKeyThumbprint_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SrcIdentityPublicKeyThumbprint {
      get { return srcIdentityPublicKeyThumbprint_; }
      set {
        srcIdentityPublicKeyThumbprint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dst_identity_public_key_thumbprint" field.</summary>
    public const int DstIdentityPublicKeyThumbprintFieldNumber = 2;
    private pb::ByteString dstIdentityPublicKeyThumbprint_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DstIdentityPublicKeyThumbprint {
      get { return dstIdentityPublicKeyThumbprint_; }
      set {
        dstIdentityPublicKeyThumbprint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 4;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DirectedMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DirectedMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcIdentityPublicKeyThumbprint != other.SrcIdentityPublicKeyThumbprint) return false;
      if (DstIdentityPublicKeyThumbprint != other.DstIdentityPublicKeyThumbprint) return false;
      if (Payload != other.Payload) return false;
      if (Signature != other.Signature) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcIdentityPublicKeyThumbprint.Length != 0) hash ^= SrcIdentityPublicKeyThumbprint.GetHashCode();
      if (DstIdentityPublicKeyThumbprint.Length != 0) hash ^= DstIdentityPublicKeyThumbprint.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcIdentityPublicKeyThumbprint.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(SrcIdentityPublicKeyThumbprint);
      }
      if (DstIdentityPublicKeyThumbprint.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(DstIdentityPublicKeyThumbprint);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Payload);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcIdentityPublicKeyThumbprint.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(SrcIdentityPublicKeyThumbprint);
      }
      if (DstIdentityPublicKeyThumbprint.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(DstIdentityPublicKeyThumbprint);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Payload);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcIdentityPublicKeyThumbprint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SrcIdentityPublicKeyThumbprint);
      }
      if (DstIdentityPublicKeyThumbprint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DstIdentityPublicKeyThumbprint);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DirectedMessage other) {
      if (other == null) {
        return;
      }
      if (other.SrcIdentityPublicKeyThumbprint.Length != 0) {
        SrcIdentityPublicKeyThumbprint = other.SrcIdentityPublicKeyThumbprint;
      }
      if (other.DstIdentityPublicKeyThumbprint.Length != 0) {
        DstIdentityPublicKeyThumbprint = other.DstIdentityPublicKeyThumbprint;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcIdentityPublicKeyThumbprint = input.ReadBytes();
            break;
          }
          case 18: {
            DstIdentityPublicKeyThumbprint = input.ReadBytes();
            break;
          }
          case 26: {
            Payload = input.ReadBytes();
            break;
          }
          case 34: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcIdentityPublicKeyThumbprint = input.ReadBytes();
            break;
          }
          case 18: {
            DstIdentityPublicKeyThumbprint = input.ReadBytes();
            break;
          }
          case 26: {
            Payload = input.ReadBytes();
            break;
          }
          case 34: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
