// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envelope_payload.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Messages {

  /// <summary>Holder for reflection information generated from envelope_payload.proto</summary>
  public static partial class EnvelopePayloadReflection {

    #region Descriptor
    /// <summary>File descriptor for envelope_payload.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnvelopePayloadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZlbnZlbG9wZV9wYXlsb2FkLnByb3RvGhZkaXJlY3RlZF9tZXNzYWdlLnBy",
            "b3RvImIKD0VudmVsb3BlUGF5bG9hZBIXCg1lcnJvcl9tZXNzYWdlGAEgASgJ",
            "SAASLAoQZGlyZWN0ZWRfbWVzc2FnZRgCIAEoCzIQLkRpcmVjdGVkTWVzc2Fn",
            "ZUgAQggKBnBheWxvZEITqgIQTHV4ZWxvdC5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Luxelot.Messages.DirectedMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Messages.EnvelopePayload), global::Luxelot.Messages.EnvelopePayload.Parser, new[]{ "ErrorMessage", "DirectedMessage" }, new[]{ "Paylod" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EnvelopePayload : pb::IMessage<EnvelopePayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnvelopePayload> _parser = new pb::MessageParser<EnvelopePayload>(() => new EnvelopePayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnvelopePayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Messages.EnvelopePayloadReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnvelopePayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnvelopePayload(EnvelopePayload other) : this() {
      switch (other.PaylodCase) {
        case PaylodOneofCase.ErrorMessage:
          ErrorMessage = other.ErrorMessage;
          break;
        case PaylodOneofCase.DirectedMessage:
          DirectedMessage = other.DirectedMessage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnvelopePayload Clone() {
      return new EnvelopePayload(this);
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return paylodCase_ == PaylodOneofCase.ErrorMessage ? (string) paylod_ : ""; }
      set {
        paylod_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        paylodCase_ = PaylodOneofCase.ErrorMessage;
      }
    }

    /// <summary>Field number for the "directed_message" field.</summary>
    public const int DirectedMessageFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Luxelot.Messages.DirectedMessage DirectedMessage {
      get { return paylodCase_ == PaylodOneofCase.DirectedMessage ? (global::Luxelot.Messages.DirectedMessage) paylod_ : null; }
      set {
        paylod_ = value;
        paylodCase_ = value == null ? PaylodOneofCase.None : PaylodOneofCase.DirectedMessage;
      }
    }

    private object paylod_;
    /// <summary>Enum of possible cases for the "paylod" oneof.</summary>
    public enum PaylodOneofCase {
      None = 0,
      ErrorMessage = 1,
      DirectedMessage = 2,
    }
    private PaylodOneofCase paylodCase_ = PaylodOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaylodOneofCase PaylodCase {
      get { return paylodCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPaylod() {
      paylodCase_ = PaylodOneofCase.None;
      paylod_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EnvelopePayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnvelopePayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorMessage != other.ErrorMessage) return false;
      if (!object.Equals(DirectedMessage, other.DirectedMessage)) return false;
      if (PaylodCase != other.PaylodCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (paylodCase_ == PaylodOneofCase.ErrorMessage) hash ^= ErrorMessage.GetHashCode();
      if (paylodCase_ == PaylodOneofCase.DirectedMessage) hash ^= DirectedMessage.GetHashCode();
      hash ^= (int) paylodCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (paylodCase_ == PaylodOneofCase.ErrorMessage) {
        output.WriteRawTag(10);
        output.WriteString(ErrorMessage);
      }
      if (paylodCase_ == PaylodOneofCase.DirectedMessage) {
        output.WriteRawTag(18);
        output.WriteMessage(DirectedMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (paylodCase_ == PaylodOneofCase.ErrorMessage) {
        output.WriteRawTag(10);
        output.WriteString(ErrorMessage);
      }
      if (paylodCase_ == PaylodOneofCase.DirectedMessage) {
        output.WriteRawTag(18);
        output.WriteMessage(DirectedMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (paylodCase_ == PaylodOneofCase.ErrorMessage) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (paylodCase_ == PaylodOneofCase.DirectedMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DirectedMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnvelopePayload other) {
      if (other == null) {
        return;
      }
      switch (other.PaylodCase) {
        case PaylodOneofCase.ErrorMessage:
          ErrorMessage = other.ErrorMessage;
          break;
        case PaylodOneofCase.DirectedMessage:
          if (DirectedMessage == null) {
            DirectedMessage = new global::Luxelot.Messages.DirectedMessage();
          }
          DirectedMessage.MergeFrom(other.DirectedMessage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 18: {
            global::Luxelot.Messages.DirectedMessage subBuilder = new global::Luxelot.Messages.DirectedMessage();
            if (paylodCase_ == PaylodOneofCase.DirectedMessage) {
              subBuilder.MergeFrom(DirectedMessage);
            }
            input.ReadMessage(subBuilder);
            DirectedMessage = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 18: {
            global::Luxelot.Messages.DirectedMessage subBuilder = new global::Luxelot.Messages.DirectedMessage();
            if (paylodCase_ == PaylodOneofCase.DirectedMessage) {
              subBuilder.MergeFrom(DirectedMessage);
            }
            input.ReadMessage(subBuilder);
            DirectedMessage = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
