// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dht_find_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Apps.DHT.Messages {

  /// <summary>Holder for reflection information generated from dht_find_response.proto</summary>
  public static partial class DhtFindResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for dht_find_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DhtFindResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdkaHRfZmluZF9yZXNwb25zZS5wcm90byJrCg9EaHRGaW5kUmVzcG9uc2US",
            "DgoGdmFsdWUxGAEgASgGEg4KBnZhbHVlMhgCIAEoBhIOCgZ2YWx1ZTMYAyAB",
            "KAYSDgoGdmFsdWU0GAQgASgGEhgKB3Jlc3VsdHMYBSADKAsyBy5SZXN1bHQi",
            "ZgoGUmVzdWx0EhIKCmlkX3B1Yl9rZXkYASABKAwSDQoFYWRkcjEYAiABKAcS",
            "DQoFYWRkcjIYAyABKAcSDQoFYWRkcjMYBCABKAcSDQoFYWRkcjQYBSABKAcS",
            "DAoEcG9ydBgGIAEoDUIcqgIZTHV4ZWxvdC5BcHBzLkRIVC5NZXNzYWdlc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Apps.DHT.Messages.DhtFindResponse), global::Luxelot.Apps.DHT.Messages.DhtFindResponse.Parser, new[]{ "Value1", "Value2", "Value3", "Value4", "Results" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Apps.DHT.Messages.Result), global::Luxelot.Apps.DHT.Messages.Result.Parser, new[]{ "IdPubKey", "Addr1", "Addr2", "Addr3", "Addr4", "Port" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DhtFindResponse : pb::IMessage<DhtFindResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DhtFindResponse> _parser = new pb::MessageParser<DhtFindResponse>(() => new DhtFindResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DhtFindResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Apps.DHT.Messages.DhtFindResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DhtFindResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DhtFindResponse(DhtFindResponse other) : this() {
      value1_ = other.value1_;
      value2_ = other.value2_;
      value3_ = other.value3_;
      value4_ = other.value4_;
      results_ = other.results_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DhtFindResponse Clone() {
      return new DhtFindResponse(this);
    }

    /// <summary>Field number for the "value1" field.</summary>
    public const int Value1FieldNumber = 1;
    private ulong value1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Value1 {
      get { return value1_; }
      set {
        value1_ = value;
      }
    }

    /// <summary>Field number for the "value2" field.</summary>
    public const int Value2FieldNumber = 2;
    private ulong value2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Value2 {
      get { return value2_; }
      set {
        value2_ = value;
      }
    }

    /// <summary>Field number for the "value3" field.</summary>
    public const int Value3FieldNumber = 3;
    private ulong value3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Value3 {
      get { return value3_; }
      set {
        value3_ = value;
      }
    }

    /// <summary>Field number for the "value4" field.</summary>
    public const int Value4FieldNumber = 4;
    private ulong value4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Value4 {
      get { return value4_; }
      set {
        value4_ = value;
      }
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Luxelot.Apps.DHT.Messages.Result> _repeated_results_codec
        = pb::FieldCodec.ForMessage(42, global::Luxelot.Apps.DHT.Messages.Result.Parser);
    private readonly pbc::RepeatedField<global::Luxelot.Apps.DHT.Messages.Result> results_ = new pbc::RepeatedField<global::Luxelot.Apps.DHT.Messages.Result>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Luxelot.Apps.DHT.Messages.Result> Results {
      get { return results_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DhtFindResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DhtFindResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value1 != other.Value1) return false;
      if (Value2 != other.Value2) return false;
      if (Value3 != other.Value3) return false;
      if (Value4 != other.Value4) return false;
      if(!results_.Equals(other.results_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Value1 != 0UL) hash ^= Value1.GetHashCode();
      if (Value2 != 0UL) hash ^= Value2.GetHashCode();
      if (Value3 != 0UL) hash ^= Value3.GetHashCode();
      if (Value4 != 0UL) hash ^= Value4.GetHashCode();
      hash ^= results_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Value1 != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(Value1);
      }
      if (Value2 != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(Value2);
      }
      if (Value3 != 0UL) {
        output.WriteRawTag(25);
        output.WriteFixed64(Value3);
      }
      if (Value4 != 0UL) {
        output.WriteRawTag(33);
        output.WriteFixed64(Value4);
      }
      results_.WriteTo(output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Value1 != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(Value1);
      }
      if (Value2 != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(Value2);
      }
      if (Value3 != 0UL) {
        output.WriteRawTag(25);
        output.WriteFixed64(Value3);
      }
      if (Value4 != 0UL) {
        output.WriteRawTag(33);
        output.WriteFixed64(Value4);
      }
      results_.WriteTo(ref output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Value1 != 0UL) {
        size += 1 + 8;
      }
      if (Value2 != 0UL) {
        size += 1 + 8;
      }
      if (Value3 != 0UL) {
        size += 1 + 8;
      }
      if (Value4 != 0UL) {
        size += 1 + 8;
      }
      size += results_.CalculateSize(_repeated_results_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DhtFindResponse other) {
      if (other == null) {
        return;
      }
      if (other.Value1 != 0UL) {
        Value1 = other.Value1;
      }
      if (other.Value2 != 0UL) {
        Value2 = other.Value2;
      }
      if (other.Value3 != 0UL) {
        Value3 = other.Value3;
      }
      if (other.Value4 != 0UL) {
        Value4 = other.Value4;
      }
      results_.Add(other.results_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Value1 = input.ReadFixed64();
            break;
          }
          case 17: {
            Value2 = input.ReadFixed64();
            break;
          }
          case 25: {
            Value3 = input.ReadFixed64();
            break;
          }
          case 33: {
            Value4 = input.ReadFixed64();
            break;
          }
          case 42: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Value1 = input.ReadFixed64();
            break;
          }
          case 17: {
            Value2 = input.ReadFixed64();
            break;
          }
          case 25: {
            Value3 = input.ReadFixed64();
            break;
          }
          case 33: {
            Value4 = input.ReadFixed64();
            break;
          }
          case 42: {
            results_.AddEntriesFrom(ref input, _repeated_results_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Result : pb::IMessage<Result>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Result> _parser = new pb::MessageParser<Result>(() => new Result());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Result> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Apps.DHT.Messages.DhtFindResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Result() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Result(Result other) : this() {
      idPubKey_ = other.idPubKey_;
      addr1_ = other.addr1_;
      addr2_ = other.addr2_;
      addr3_ = other.addr3_;
      addr4_ = other.addr4_;
      port_ = other.port_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Result Clone() {
      return new Result(this);
    }

    /// <summary>Field number for the "id_pub_key" field.</summary>
    public const int IdPubKeyFieldNumber = 1;
    private pb::ByteString idPubKey_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString IdPubKey {
      get { return idPubKey_; }
      set {
        idPubKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addr1" field.</summary>
    public const int Addr1FieldNumber = 2;
    private uint addr1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr1 {
      get { return addr1_; }
      set {
        addr1_ = value;
      }
    }

    /// <summary>Field number for the "addr2" field.</summary>
    public const int Addr2FieldNumber = 3;
    private uint addr2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr2 {
      get { return addr2_; }
      set {
        addr2_ = value;
      }
    }

    /// <summary>Field number for the "addr3" field.</summary>
    public const int Addr3FieldNumber = 4;
    private uint addr3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr3 {
      get { return addr3_; }
      set {
        addr3_ = value;
      }
    }

    /// <summary>Field number for the "addr4" field.</summary>
    public const int Addr4FieldNumber = 5;
    private uint addr4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr4 {
      get { return addr4_; }
      set {
        addr4_ = value;
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 6;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Result);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Result other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdPubKey != other.IdPubKey) return false;
      if (Addr1 != other.Addr1) return false;
      if (Addr2 != other.Addr2) return false;
      if (Addr3 != other.Addr3) return false;
      if (Addr4 != other.Addr4) return false;
      if (Port != other.Port) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdPubKey.Length != 0) hash ^= IdPubKey.GetHashCode();
      if (Addr1 != 0) hash ^= Addr1.GetHashCode();
      if (Addr2 != 0) hash ^= Addr2.GetHashCode();
      if (Addr3 != 0) hash ^= Addr3.GetHashCode();
      if (Addr4 != 0) hash ^= Addr4.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdPubKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(IdPubKey);
      }
      if (Addr1 != 0) {
        output.WriteRawTag(21);
        output.WriteFixed32(Addr1);
      }
      if (Addr2 != 0) {
        output.WriteRawTag(29);
        output.WriteFixed32(Addr2);
      }
      if (Addr3 != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(Addr3);
      }
      if (Addr4 != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Addr4);
      }
      if (Port != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdPubKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(IdPubKey);
      }
      if (Addr1 != 0) {
        output.WriteRawTag(21);
        output.WriteFixed32(Addr1);
      }
      if (Addr2 != 0) {
        output.WriteRawTag(29);
        output.WriteFixed32(Addr2);
      }
      if (Addr3 != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(Addr3);
      }
      if (Addr4 != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Addr4);
      }
      if (Port != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdPubKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(IdPubKey);
      }
      if (Addr1 != 0) {
        size += 1 + 4;
      }
      if (Addr2 != 0) {
        size += 1 + 4;
      }
      if (Addr3 != 0) {
        size += 1 + 4;
      }
      if (Addr4 != 0) {
        size += 1 + 4;
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Result other) {
      if (other == null) {
        return;
      }
      if (other.IdPubKey.Length != 0) {
        IdPubKey = other.IdPubKey;
      }
      if (other.Addr1 != 0) {
        Addr1 = other.Addr1;
      }
      if (other.Addr2 != 0) {
        Addr2 = other.Addr2;
      }
      if (other.Addr3 != 0) {
        Addr3 = other.Addr3;
      }
      if (other.Addr4 != 0) {
        Addr4 = other.Addr4;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdPubKey = input.ReadBytes();
            break;
          }
          case 21: {
            Addr1 = input.ReadFixed32();
            break;
          }
          case 29: {
            Addr2 = input.ReadFixed32();
            break;
          }
          case 37: {
            Addr3 = input.ReadFixed32();
            break;
          }
          case 45: {
            Addr4 = input.ReadFixed32();
            break;
          }
          case 48: {
            Port = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdPubKey = input.ReadBytes();
            break;
          }
          case 21: {
            Addr1 = input.ReadFixed32();
            break;
          }
          case 29: {
            Addr2 = input.ReadFixed32();
            break;
          }
          case 37: {
            Addr3 = input.ReadFixed32();
            break;
          }
          case 45: {
            Addr4 = input.ReadFixed32();
            break;
          }
          case 48: {
            Port = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
