// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: download_ready.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Apps.FserveApp.Messages {

  /// <summary>Holder for reflection information generated from download_ready.proto</summary>
  public static partial class DownloadReadyReflection {

    #region Descriptor
    /// <summary>File descriptor for download_ready.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DownloadReadyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRkb3dubG9hZF9yZWFkeS5wcm90byKkAgoNRG93bmxvYWRSZWFkeRIMCgRm",
            "aWxlGAEgASgJEg4KBnRpY2tldBgCIAEoCRIMCgRzaXplGAMgASgEEgwKBGhh",
            "c2gYBCABKAwSFAoMaXNfZW5jcnlwdGVkGAUgASgIEhUKDWlzX2RpcmVjdF91",
            "ZHAYBiABKAgSGAoQZGlyZWN0X3VkcF9hZGRyMRgHIAEoBxIYChBkaXJlY3Rf",
            "dWRwX2FkZHIyGAggASgHEhgKEGRpcmVjdF91ZHBfYWRkcjMYCSABKAcSGAoQ",
            "ZGlyZWN0X3VkcF9hZGRyNBgKIAEoBxIXCg9kaXJlY3RfdWRwX3BvcnQYCyAB",
            "KAUSEwoLY2h1bmtfY291bnQYDCABKA0SFgoGY2h1bmtzGA0gAygLMgYuQ2h1",
            "bmsiMAoFQ2h1bmsSCwoDc2VxGAEgASgNEgwKBHNpemUYAiABKAQSDAoEaGFz",
            "aBgDIAEoDEIiqgIfTHV4ZWxvdC5BcHBzLkZzZXJ2ZUFwcC5NZXNzYWdlc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Apps.FserveApp.Messages.DownloadReady), global::Luxelot.Apps.FserveApp.Messages.DownloadReady.Parser, new[]{ "File", "Ticket", "Size", "Hash", "IsEncrypted", "IsDirectUdp", "DirectUdpAddr1", "DirectUdpAddr2", "DirectUdpAddr3", "DirectUdpAddr4", "DirectUdpPort", "ChunkCount", "Chunks" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Apps.FserveApp.Messages.Chunk), global::Luxelot.Apps.FserveApp.Messages.Chunk.Parser, new[]{ "Seq", "Size", "Hash" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DownloadReady : pb::IMessage<DownloadReady>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DownloadReady> _parser = new pb::MessageParser<DownloadReady>(() => new DownloadReady());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DownloadReady> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Apps.FserveApp.Messages.DownloadReadyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DownloadReady() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DownloadReady(DownloadReady other) : this() {
      file_ = other.file_;
      ticket_ = other.ticket_;
      size_ = other.size_;
      hash_ = other.hash_;
      isEncrypted_ = other.isEncrypted_;
      isDirectUdp_ = other.isDirectUdp_;
      directUdpAddr1_ = other.directUdpAddr1_;
      directUdpAddr2_ = other.directUdpAddr2_;
      directUdpAddr3_ = other.directUdpAddr3_;
      directUdpAddr4_ = other.directUdpAddr4_;
      directUdpPort_ = other.directUdpPort_;
      chunkCount_ = other.chunkCount_;
      chunks_ = other.chunks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DownloadReady Clone() {
      return new DownloadReady(this);
    }

    /// <summary>Field number for the "file" field.</summary>
    public const int FileFieldNumber = 1;
    private string file_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string File {
      get { return file_; }
      set {
        file_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ticket" field.</summary>
    public const int TicketFieldNumber = 2;
    private string ticket_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ticket {
      get { return ticket_; }
      set {
        ticket_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 3;
    private ulong size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "hash" field.</summary>
    public const int HashFieldNumber = 4;
    private pb::ByteString hash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_encrypted" field.</summary>
    public const int IsEncryptedFieldNumber = 5;
    private bool isEncrypted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsEncrypted {
      get { return isEncrypted_; }
      set {
        isEncrypted_ = value;
      }
    }

    /// <summary>Field number for the "is_direct_udp" field.</summary>
    public const int IsDirectUdpFieldNumber = 6;
    private bool isDirectUdp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDirectUdp {
      get { return isDirectUdp_; }
      set {
        isDirectUdp_ = value;
      }
    }

    /// <summary>Field number for the "direct_udp_addr1" field.</summary>
    public const int DirectUdpAddr1FieldNumber = 7;
    private uint directUdpAddr1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DirectUdpAddr1 {
      get { return directUdpAddr1_; }
      set {
        directUdpAddr1_ = value;
      }
    }

    /// <summary>Field number for the "direct_udp_addr2" field.</summary>
    public const int DirectUdpAddr2FieldNumber = 8;
    private uint directUdpAddr2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DirectUdpAddr2 {
      get { return directUdpAddr2_; }
      set {
        directUdpAddr2_ = value;
      }
    }

    /// <summary>Field number for the "direct_udp_addr3" field.</summary>
    public const int DirectUdpAddr3FieldNumber = 9;
    private uint directUdpAddr3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DirectUdpAddr3 {
      get { return directUdpAddr3_; }
      set {
        directUdpAddr3_ = value;
      }
    }

    /// <summary>Field number for the "direct_udp_addr4" field.</summary>
    public const int DirectUdpAddr4FieldNumber = 10;
    private uint directUdpAddr4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DirectUdpAddr4 {
      get { return directUdpAddr4_; }
      set {
        directUdpAddr4_ = value;
      }
    }

    /// <summary>Field number for the "direct_udp_port" field.</summary>
    public const int DirectUdpPortFieldNumber = 11;
    private int directUdpPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DirectUdpPort {
      get { return directUdpPort_; }
      set {
        directUdpPort_ = value;
      }
    }

    /// <summary>Field number for the "chunk_count" field.</summary>
    public const int ChunkCountFieldNumber = 12;
    private uint chunkCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChunkCount {
      get { return chunkCount_; }
      set {
        chunkCount_ = value;
      }
    }

    /// <summary>Field number for the "chunks" field.</summary>
    public const int ChunksFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Luxelot.Apps.FserveApp.Messages.Chunk> _repeated_chunks_codec
        = pb::FieldCodec.ForMessage(106, global::Luxelot.Apps.FserveApp.Messages.Chunk.Parser);
    private readonly pbc::RepeatedField<global::Luxelot.Apps.FserveApp.Messages.Chunk> chunks_ = new pbc::RepeatedField<global::Luxelot.Apps.FserveApp.Messages.Chunk>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Luxelot.Apps.FserveApp.Messages.Chunk> Chunks {
      get { return chunks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DownloadReady);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DownloadReady other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (File != other.File) return false;
      if (Ticket != other.Ticket) return false;
      if (Size != other.Size) return false;
      if (Hash != other.Hash) return false;
      if (IsEncrypted != other.IsEncrypted) return false;
      if (IsDirectUdp != other.IsDirectUdp) return false;
      if (DirectUdpAddr1 != other.DirectUdpAddr1) return false;
      if (DirectUdpAddr2 != other.DirectUdpAddr2) return false;
      if (DirectUdpAddr3 != other.DirectUdpAddr3) return false;
      if (DirectUdpAddr4 != other.DirectUdpAddr4) return false;
      if (DirectUdpPort != other.DirectUdpPort) return false;
      if (ChunkCount != other.ChunkCount) return false;
      if(!chunks_.Equals(other.chunks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (File.Length != 0) hash ^= File.GetHashCode();
      if (Ticket.Length != 0) hash ^= Ticket.GetHashCode();
      if (Size != 0UL) hash ^= Size.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (IsEncrypted != false) hash ^= IsEncrypted.GetHashCode();
      if (IsDirectUdp != false) hash ^= IsDirectUdp.GetHashCode();
      if (DirectUdpAddr1 != 0) hash ^= DirectUdpAddr1.GetHashCode();
      if (DirectUdpAddr2 != 0) hash ^= DirectUdpAddr2.GetHashCode();
      if (DirectUdpAddr3 != 0) hash ^= DirectUdpAddr3.GetHashCode();
      if (DirectUdpAddr4 != 0) hash ^= DirectUdpAddr4.GetHashCode();
      if (DirectUdpPort != 0) hash ^= DirectUdpPort.GetHashCode();
      if (ChunkCount != 0) hash ^= ChunkCount.GetHashCode();
      hash ^= chunks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (File.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(File);
      }
      if (Ticket.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Ticket);
      }
      if (Size != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Size);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Hash);
      }
      if (IsEncrypted != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsEncrypted);
      }
      if (IsDirectUdp != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsDirectUdp);
      }
      if (DirectUdpAddr1 != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(DirectUdpAddr1);
      }
      if (DirectUdpAddr2 != 0) {
        output.WriteRawTag(69);
        output.WriteFixed32(DirectUdpAddr2);
      }
      if (DirectUdpAddr3 != 0) {
        output.WriteRawTag(77);
        output.WriteFixed32(DirectUdpAddr3);
      }
      if (DirectUdpAddr4 != 0) {
        output.WriteRawTag(85);
        output.WriteFixed32(DirectUdpAddr4);
      }
      if (DirectUdpPort != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(DirectUdpPort);
      }
      if (ChunkCount != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(ChunkCount);
      }
      chunks_.WriteTo(output, _repeated_chunks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (File.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(File);
      }
      if (Ticket.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Ticket);
      }
      if (Size != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Size);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Hash);
      }
      if (IsEncrypted != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsEncrypted);
      }
      if (IsDirectUdp != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsDirectUdp);
      }
      if (DirectUdpAddr1 != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(DirectUdpAddr1);
      }
      if (DirectUdpAddr2 != 0) {
        output.WriteRawTag(69);
        output.WriteFixed32(DirectUdpAddr2);
      }
      if (DirectUdpAddr3 != 0) {
        output.WriteRawTag(77);
        output.WriteFixed32(DirectUdpAddr3);
      }
      if (DirectUdpAddr4 != 0) {
        output.WriteRawTag(85);
        output.WriteFixed32(DirectUdpAddr4);
      }
      if (DirectUdpPort != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(DirectUdpPort);
      }
      if (ChunkCount != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(ChunkCount);
      }
      chunks_.WriteTo(ref output, _repeated_chunks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (File.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(File);
      }
      if (Ticket.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ticket);
      }
      if (Size != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Size);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
      }
      if (IsEncrypted != false) {
        size += 1 + 1;
      }
      if (IsDirectUdp != false) {
        size += 1 + 1;
      }
      if (DirectUdpAddr1 != 0) {
        size += 1 + 4;
      }
      if (DirectUdpAddr2 != 0) {
        size += 1 + 4;
      }
      if (DirectUdpAddr3 != 0) {
        size += 1 + 4;
      }
      if (DirectUdpAddr4 != 0) {
        size += 1 + 4;
      }
      if (DirectUdpPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DirectUdpPort);
      }
      if (ChunkCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChunkCount);
      }
      size += chunks_.CalculateSize(_repeated_chunks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DownloadReady other) {
      if (other == null) {
        return;
      }
      if (other.File.Length != 0) {
        File = other.File;
      }
      if (other.Ticket.Length != 0) {
        Ticket = other.Ticket;
      }
      if (other.Size != 0UL) {
        Size = other.Size;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      if (other.IsEncrypted != false) {
        IsEncrypted = other.IsEncrypted;
      }
      if (other.IsDirectUdp != false) {
        IsDirectUdp = other.IsDirectUdp;
      }
      if (other.DirectUdpAddr1 != 0) {
        DirectUdpAddr1 = other.DirectUdpAddr1;
      }
      if (other.DirectUdpAddr2 != 0) {
        DirectUdpAddr2 = other.DirectUdpAddr2;
      }
      if (other.DirectUdpAddr3 != 0) {
        DirectUdpAddr3 = other.DirectUdpAddr3;
      }
      if (other.DirectUdpAddr4 != 0) {
        DirectUdpAddr4 = other.DirectUdpAddr4;
      }
      if (other.DirectUdpPort != 0) {
        DirectUdpPort = other.DirectUdpPort;
      }
      if (other.ChunkCount != 0) {
        ChunkCount = other.ChunkCount;
      }
      chunks_.Add(other.chunks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            File = input.ReadString();
            break;
          }
          case 18: {
            Ticket = input.ReadString();
            break;
          }
          case 24: {
            Size = input.ReadUInt64();
            break;
          }
          case 34: {
            Hash = input.ReadBytes();
            break;
          }
          case 40: {
            IsEncrypted = input.ReadBool();
            break;
          }
          case 48: {
            IsDirectUdp = input.ReadBool();
            break;
          }
          case 61: {
            DirectUdpAddr1 = input.ReadFixed32();
            break;
          }
          case 69: {
            DirectUdpAddr2 = input.ReadFixed32();
            break;
          }
          case 77: {
            DirectUdpAddr3 = input.ReadFixed32();
            break;
          }
          case 85: {
            DirectUdpAddr4 = input.ReadFixed32();
            break;
          }
          case 88: {
            DirectUdpPort = input.ReadInt32();
            break;
          }
          case 96: {
            ChunkCount = input.ReadUInt32();
            break;
          }
          case 106: {
            chunks_.AddEntriesFrom(input, _repeated_chunks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            File = input.ReadString();
            break;
          }
          case 18: {
            Ticket = input.ReadString();
            break;
          }
          case 24: {
            Size = input.ReadUInt64();
            break;
          }
          case 34: {
            Hash = input.ReadBytes();
            break;
          }
          case 40: {
            IsEncrypted = input.ReadBool();
            break;
          }
          case 48: {
            IsDirectUdp = input.ReadBool();
            break;
          }
          case 61: {
            DirectUdpAddr1 = input.ReadFixed32();
            break;
          }
          case 69: {
            DirectUdpAddr2 = input.ReadFixed32();
            break;
          }
          case 77: {
            DirectUdpAddr3 = input.ReadFixed32();
            break;
          }
          case 85: {
            DirectUdpAddr4 = input.ReadFixed32();
            break;
          }
          case 88: {
            DirectUdpPort = input.ReadInt32();
            break;
          }
          case 96: {
            ChunkCount = input.ReadUInt32();
            break;
          }
          case 106: {
            chunks_.AddEntriesFrom(ref input, _repeated_chunks_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Chunk : pb::IMessage<Chunk>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Chunk> _parser = new pb::MessageParser<Chunk>(() => new Chunk());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Chunk> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Apps.FserveApp.Messages.DownloadReadyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chunk() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chunk(Chunk other) : this() {
      seq_ = other.seq_;
      size_ = other.size_;
      hash_ = other.hash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chunk Clone() {
      return new Chunk(this);
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 1;
    private uint seq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 2;
    private ulong size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "hash" field.</summary>
    public const int HashFieldNumber = 3;
    private pb::ByteString hash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Chunk);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Chunk other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Seq != other.Seq) return false;
      if (Size != other.Size) return false;
      if (Hash != other.Hash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Seq != 0) hash ^= Seq.GetHashCode();
      if (Size != 0UL) hash ^= Size.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Seq != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Seq);
      }
      if (Size != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Size);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Seq != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Seq);
      }
      if (Size != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Size);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Seq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Seq);
      }
      if (Size != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Size);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Chunk other) {
      if (other == null) {
        return;
      }
      if (other.Seq != 0) {
        Seq = other.Seq;
      }
      if (other.Size != 0UL) {
        Size = other.Size;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Seq = input.ReadUInt32();
            break;
          }
          case 16: {
            Size = input.ReadUInt64();
            break;
          }
          case 26: {
            Hash = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Seq = input.ReadUInt32();
            break;
          }
          case 16: {
            Size = input.ReadUInt64();
            break;
          }
          case 26: {
            Hash = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
