// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ack.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Messages {

  /// <summary>Holder for reflection information generated from ack.proto</summary>
  public static partial class AckReflection {

    #region Descriptor
    /// <summary>File descriptor for ack.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AckReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglhY2sucHJvdG8ifAoDQWNrEhAKCHByb3RfdmVyGAEgASgNEhMKC2NpcGhl",
            "cl90ZXh0GAIgASgMEhIKCmlkX3B1Yl9rZXkYAyABKAwSDQoFYWRkcjEYBCAB",
            "KAcSDQoFYWRkcjIYBSABKAcSDQoFYWRkcjMYBiABKAcSDQoFYWRkcjQYByAB",
            "KAdCE6oCEEx1eGVsb3QuTWVzc2FnZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Messages.Ack), global::Luxelot.Messages.Ack.Parser, new[]{ "ProtVer", "CipherText", "IdPubKey", "Addr1", "Addr2", "Addr3", "Addr4" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Ack : pb::IMessage<Ack>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ack> _parser = new pb::MessageParser<Ack>(() => new Ack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Messages.AckReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ack(Ack other) : this() {
      protVer_ = other.protVer_;
      cipherText_ = other.cipherText_;
      idPubKey_ = other.idPubKey_;
      addr1_ = other.addr1_;
      addr2_ = other.addr2_;
      addr3_ = other.addr3_;
      addr4_ = other.addr4_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ack Clone() {
      return new Ack(this);
    }

    /// <summary>Field number for the "prot_ver" field.</summary>
    public const int ProtVerFieldNumber = 1;
    private uint protVer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtVer {
      get { return protVer_; }
      set {
        protVer_ = value;
      }
    }

    /// <summary>Field number for the "cipher_text" field.</summary>
    public const int CipherTextFieldNumber = 2;
    private pb::ByteString cipherText_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString CipherText {
      get { return cipherText_; }
      set {
        cipherText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_pub_key" field.</summary>
    public const int IdPubKeyFieldNumber = 3;
    private pb::ByteString idPubKey_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString IdPubKey {
      get { return idPubKey_; }
      set {
        idPubKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addr1" field.</summary>
    public const int Addr1FieldNumber = 4;
    private uint addr1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr1 {
      get { return addr1_; }
      set {
        addr1_ = value;
      }
    }

    /// <summary>Field number for the "addr2" field.</summary>
    public const int Addr2FieldNumber = 5;
    private uint addr2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr2 {
      get { return addr2_; }
      set {
        addr2_ = value;
      }
    }

    /// <summary>Field number for the "addr3" field.</summary>
    public const int Addr3FieldNumber = 6;
    private uint addr3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr3 {
      get { return addr3_; }
      set {
        addr3_ = value;
      }
    }

    /// <summary>Field number for the "addr4" field.</summary>
    public const int Addr4FieldNumber = 7;
    private uint addr4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addr4 {
      get { return addr4_; }
      set {
        addr4_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtVer != other.ProtVer) return false;
      if (CipherText != other.CipherText) return false;
      if (IdPubKey != other.IdPubKey) return false;
      if (Addr1 != other.Addr1) return false;
      if (Addr2 != other.Addr2) return false;
      if (Addr3 != other.Addr3) return false;
      if (Addr4 != other.Addr4) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtVer != 0) hash ^= ProtVer.GetHashCode();
      if (CipherText.Length != 0) hash ^= CipherText.GetHashCode();
      if (IdPubKey.Length != 0) hash ^= IdPubKey.GetHashCode();
      if (Addr1 != 0) hash ^= Addr1.GetHashCode();
      if (Addr2 != 0) hash ^= Addr2.GetHashCode();
      if (Addr3 != 0) hash ^= Addr3.GetHashCode();
      if (Addr4 != 0) hash ^= Addr4.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtVer != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtVer);
      }
      if (CipherText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(CipherText);
      }
      if (IdPubKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(IdPubKey);
      }
      if (Addr1 != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(Addr1);
      }
      if (Addr2 != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Addr2);
      }
      if (Addr3 != 0) {
        output.WriteRawTag(53);
        output.WriteFixed32(Addr3);
      }
      if (Addr4 != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Addr4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtVer != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtVer);
      }
      if (CipherText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(CipherText);
      }
      if (IdPubKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(IdPubKey);
      }
      if (Addr1 != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(Addr1);
      }
      if (Addr2 != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Addr2);
      }
      if (Addr3 != 0) {
        output.WriteRawTag(53);
        output.WriteFixed32(Addr3);
      }
      if (Addr4 != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(Addr4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtVer != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtVer);
      }
      if (CipherText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CipherText);
      }
      if (IdPubKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(IdPubKey);
      }
      if (Addr1 != 0) {
        size += 1 + 4;
      }
      if (Addr2 != 0) {
        size += 1 + 4;
      }
      if (Addr3 != 0) {
        size += 1 + 4;
      }
      if (Addr4 != 0) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ack other) {
      if (other == null) {
        return;
      }
      if (other.ProtVer != 0) {
        ProtVer = other.ProtVer;
      }
      if (other.CipherText.Length != 0) {
        CipherText = other.CipherText;
      }
      if (other.IdPubKey.Length != 0) {
        IdPubKey = other.IdPubKey;
      }
      if (other.Addr1 != 0) {
        Addr1 = other.Addr1;
      }
      if (other.Addr2 != 0) {
        Addr2 = other.Addr2;
      }
      if (other.Addr3 != 0) {
        Addr3 = other.Addr3;
      }
      if (other.Addr4 != 0) {
        Addr4 = other.Addr4;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtVer = input.ReadUInt32();
            break;
          }
          case 18: {
            CipherText = input.ReadBytes();
            break;
          }
          case 26: {
            IdPubKey = input.ReadBytes();
            break;
          }
          case 37: {
            Addr1 = input.ReadFixed32();
            break;
          }
          case 45: {
            Addr2 = input.ReadFixed32();
            break;
          }
          case 53: {
            Addr3 = input.ReadFixed32();
            break;
          }
          case 61: {
            Addr4 = input.ReadFixed32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtVer = input.ReadUInt32();
            break;
          }
          case 18: {
            CipherText = input.ReadBytes();
            break;
          }
          case 26: {
            IdPubKey = input.ReadBytes();
            break;
          }
          case 37: {
            Addr1 = input.ReadFixed32();
            break;
          }
          case 45: {
            Addr2 = input.ReadFixed32();
            break;
          }
          case 53: {
            Addr3 = input.ReadFixed32();
            break;
          }
          case 61: {
            Addr4 = input.ReadFixed32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
