// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_destination_unreachable.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Luxelot.Messages {

  /// <summary>Holder for reflection information generated from error_destination_unreachable.proto</summary>
  public static partial class ErrorDestinationUnreachableReflection {

    #region Descriptor
    /// <summary>File descriptor for error_destination_unreachable.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorDestinationUnreachableReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNlcnJvcl9kZXN0aW5hdGlvbl91bnJlYWNoYWJsZS5wcm90byJkChtFcnJv",
            "ckRlc3RpbmF0aW9uVW5yZWFjaGFibGUSJwofdW5yZWFjaGFibGVfaWRlbnRp",
            "dHlfdGh1bWJwcmludBgBIAEoDBIcChRuZWlnaGJvcl90aHVtYnByaW50cxgC",
            "IAMoDEITqgIQTHV4ZWxvdC5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Luxelot.Messages.ErrorDestinationUnreachable), global::Luxelot.Messages.ErrorDestinationUnreachable.Parser, new[]{ "UnreachableIdentityThumbprint", "NeighborThumbprints" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ErrorDestinationUnreachable : pb::IMessage<ErrorDestinationUnreachable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ErrorDestinationUnreachable> _parser = new pb::MessageParser<ErrorDestinationUnreachable>(() => new ErrorDestinationUnreachable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ErrorDestinationUnreachable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Luxelot.Messages.ErrorDestinationUnreachableReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorDestinationUnreachable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorDestinationUnreachable(ErrorDestinationUnreachable other) : this() {
      unreachableIdentityThumbprint_ = other.unreachableIdentityThumbprint_;
      neighborThumbprints_ = other.neighborThumbprints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorDestinationUnreachable Clone() {
      return new ErrorDestinationUnreachable(this);
    }

    /// <summary>Field number for the "unreachable_identity_thumbprint" field.</summary>
    public const int UnreachableIdentityThumbprintFieldNumber = 1;
    private pb::ByteString unreachableIdentityThumbprint_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString UnreachableIdentityThumbprint {
      get { return unreachableIdentityThumbprint_; }
      set {
        unreachableIdentityThumbprint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "neighbor_thumbprints" field.</summary>
    public const int NeighborThumbprintsFieldNumber = 2;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_neighborThumbprints_codec
        = pb::FieldCodec.ForBytes(18);
    private readonly pbc::RepeatedField<pb::ByteString> neighborThumbprints_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> NeighborThumbprints {
      get { return neighborThumbprints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ErrorDestinationUnreachable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ErrorDestinationUnreachable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnreachableIdentityThumbprint != other.UnreachableIdentityThumbprint) return false;
      if(!neighborThumbprints_.Equals(other.neighborThumbprints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UnreachableIdentityThumbprint.Length != 0) hash ^= UnreachableIdentityThumbprint.GetHashCode();
      hash ^= neighborThumbprints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UnreachableIdentityThumbprint.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(UnreachableIdentityThumbprint);
      }
      neighborThumbprints_.WriteTo(output, _repeated_neighborThumbprints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UnreachableIdentityThumbprint.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(UnreachableIdentityThumbprint);
      }
      neighborThumbprints_.WriteTo(ref output, _repeated_neighborThumbprints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UnreachableIdentityThumbprint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(UnreachableIdentityThumbprint);
      }
      size += neighborThumbprints_.CalculateSize(_repeated_neighborThumbprints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ErrorDestinationUnreachable other) {
      if (other == null) {
        return;
      }
      if (other.UnreachableIdentityThumbprint.Length != 0) {
        UnreachableIdentityThumbprint = other.UnreachableIdentityThumbprint;
      }
      neighborThumbprints_.Add(other.neighborThumbprints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UnreachableIdentityThumbprint = input.ReadBytes();
            break;
          }
          case 18: {
            neighborThumbprints_.AddEntriesFrom(input, _repeated_neighborThumbprints_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UnreachableIdentityThumbprint = input.ReadBytes();
            break;
          }
          case 18: {
            neighborThumbprints_.AddEntriesFrom(ref input, _repeated_neighborThumbprints_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
